### ISSUE TITLE
 Namespace not specified. Specify a namespace in photo_gallery-2.2.1\android\build.gradle

### ISSUE THREAD

**Issue by AdamsEstiff** [Firelands128/photo_gallery#78]
This problem occurs when I had to migrate to Kotlin 2.0.10 and therefore update my gradle completely, when trying to create the apk I get the following error:
> Could not create an instance of type com.android.build.api.variant.impl.LibraryVariantBuilderImpl.
> Namespace not specified. Specify a namespace in the module's build file: photo_gallery-2.2.1\android\build.gradle. See https://d.android.com/r/tools/upgrade-assistant/set-namespace for information about setting the namespace.
I omit part of the path of the problem for obvious reasons, please need a solution to the problem, thank you very much.

There needs to be a new value in the android {...} block:

android {
    compileSdkVersion 34
    ...
    namespace 'com.example.app'
}
This is located in app/build.gradle

**Comment by DeuMiAn** [comment]
```
dependency_overrides:
  photo_gallery:
    git:
      url: https://github.com/DeuMiAn/photo_gallery.git
      ref: master
```

I temporarily modified it using a fork. If you want to use it, please use it
